// benchmarks/eval/projects/shop/svelte/CartView.svelte
<script lang="ts">
  import type { CartItem } from "./data";
  import CartItemRow from "./CartItemRow.svelte";
  import Summary from "./Summary.svelte";

  let { cart, onChangeQty, onClear }: { cart: CartItem[]; onChangeQty: (id: number, delta: number) => void; onClear: () => void } = $props();
</script>

{#if cart.length === 0}
  <span class="text-gray-500">El carrito está vacío</span>
{:else}
  <div class="flex flex-col gap-2">
    {#each cart as item (item.product.id)}
      <CartItemRow {item} onChangeQty={(d) => onChangeQty(item.product.id, d)} />
    {/each}
    <Summary {cart} {onClear} />
  </div>
{/if}

// benchmarks/eval/projects/shop/vue/CartView.vue
<script setup lang="ts">
import type { CartItem } from "./data";
import CartItemRow from "./CartItemRow.vue";
import Summary from "./Summary.vue";

defineProps<{ cart: CartItem[] }>();
const emit = defineEmits<{ changeQty: [id: number, delta: number]; clear: [] }>();
</script>

<template>
  <span v-if="cart.length === 0" class="text-gray-500">El carrito está vacío</span>
  <div v-else class="flex flex-col gap-2">
    <CartItemRow v-for="item in cart" :key="item.product.id" :item="item" @change-qty="(d) => emit('changeQty', item.product.id, d)" />
    <Summary :cart="cart" @clear="emit('clear')" />
  </div>
</template>
