// benchmarks/eval/refs/fs-products/react/App.tsx
import { useEffect, useState } from "react";

type Product = { id: string; name: string; code: string; price: number };

export default function App() {
  const [products, setProducts] = useState<Product[]>([]);
  const [name, setName] = useState("");
  const [code, setCode] = useState("");
  const [price, setPrice] = useState("");
  const [error, setError] = useState("");

  const load = () => fetch("/api/products").then((r) => r.json()).then(setProducts);
  useEffect(() => { load(); }, []);

  async function save() {
    const res = await fetch("/api/products", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ name, code, price: Number(price) }),
    });
    setError(res.ok ? "" : (await res.json()).error);
    load();
  }

  return (
    <div className="flex flex-col gap-3">
      <input placeholder="Nombre" value={name} onChange={(e) => setName(e.target.value)} />
      <input placeholder="Código" value={code} onChange={(e) => setCode(e.target.value)} />
      <input placeholder="Precio" type="number" value={price} onChange={(e) => setPrice(e.target.value)} />
      <button onClick={save}>Guardar</button>
      {error && <span className="text-red-600">{error}</span>}
      {products.map((p) => <p key={p.id}>{p.name} ({p.code})</p>)}
    </div>
  );
}

// benchmarks/eval/refs/fs-products/vue/App.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";

type Product = { id: string; name: string; code: string; price: number };

const products = ref<Product[]>([]);
const name = ref("");
const code = ref("");
const price = ref("");
const error = ref("");

async function load() {
  products.value = await (await fetch("/api/products")).json();
}
onMounted(load);

async function save() {
  const res = await fetch("/api/products", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ name: name.value, code: code.value, price: Number(price.value) }),
  });
  error.value = res.ok ? "" : (await res.json()).error;
  await load();
}
</script>

<template>
  <div class="flex flex-col gap-3">
    <input v-model="name" placeholder="Nombre" />
    <input v-model="code" placeholder="Código" />
    <input v-model="price" placeholder="Precio" />
    <button @click="save">Guardar</button>
    <span v-if="error" class="text-red-600">{{ error }}</span>
    <p v-for="p in products" :key="p.id">{{ p.name }} ({{ p.code }})</p>
  </div>
</template>
