// benchmarks/eval/projects/shop/vue/App.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { PRODUCTS, type CartItem, type Product } from "./data";
import Header from "./Header.vue";
import Nav from "./Nav.vue";
import Catalog from "./Catalog.vue";
import CartView from "./CartView.vue";
import Footer from "./Footer.vue";

const products = ref<Product[]>(PRODUCTS.map((p) => ({ ...p })));
const cart = ref<CartItem[]>([]);
const tab = ref<"catalog" | "cart">("catalog");
const count = computed(() => cart.value.reduce((n, i) => n + i.qty, 0));

function add(product: Product) {
  const found = cart.value.find((i) => i.product.id === product.id);
  if (found) found.qty++;
  else cart.value.push({ product, qty: 1 });
}

function changeQty(id: number, delta: number) {
  cart.value = cart.value.map((i) => (i.product.id === id ? { ...i, qty: i.qty + delta } : i)).filter((i) => i.qty > 0);
}
</script>

<template>
  <div class="flex flex-col gap-4 p-4">
    <Header :count="count" />
    <Nav :tab="tab" @change="(t) => (tab = t)" />
    <Catalog v-if="tab === 'catalog'" :products="products" @add="add" />
    <CartView v-else :cart="cart" @change-qty="changeQty" @clear="cart = []" />
    <Footer />
  </div>
</template>

// benchmarks/eval/projects/shop/svelte/App.svelte
<script lang="ts">
  import { PRODUCTS, type CartItem, type Product } from "./data";
  import Header from "./Header.svelte";
  import Nav from "./Nav.svelte";
  import Catalog from "./Catalog.svelte";
  import CartView from "./CartView.svelte";
  import Footer from "./Footer.svelte";

  let products = $state<Product[]>(PRODUCTS.map((p) => ({ ...p })));
  let cart = $state<CartItem[]>([]);
  let tab = $state<"catalog" | "cart">("catalog");
  let count = $derived(cart.reduce((n, i) => n + i.qty, 0));

  function add(product: Product) {
    const found = cart.find((i) => i.product.id === product.id);
    if (found) found.qty++;
    else cart.push({ product, qty: 1 });
  }

  function changeQty(id: number, delta: number) {
    cart = cart.map((i) => (i.product.id === id ? { ...i, qty: i.qty + delta } : i)).filter((i) => i.qty > 0);
  }
</script>

<div class="flex flex-col gap-4 p-4">
  <Header {count} />
  <Nav {tab} onChange={(t) => (tab = t)} />
  {#if tab === "catalog"}
    <Catalog {products} onAdd={add} />
  {:else}
    <CartView {cart} onChangeQty={changeQty} onClear={() => (cart = [])} />
  {/if}
  <Footer />
</div>
