// benchmarks/eval/refs/fs-blog/vue/App.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";

type Author = { id: string; name: string };
type Post = { id: string; title: string; author: Author | null };

const authors = ref<Author[]>([]);
const posts = ref<Post[]>([]);
const name = ref("");
const title = ref("");
const authorId = ref("");
const error = ref("");

const json = (method: string, body: unknown) => ({ method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) });

async function load() {
  authors.value = await (await fetch("/api/authors")).json();
  posts.value = await (await fetch("/api/posts")).json();
}
onMounted(load);

async function createAuthor() {
  await fetch("/api/authors", json("POST", { name: name.value }));
  name.value = "";
  await load();
}

async function removeAuthor(id: string) {
  const res = await fetch(`/api/authors/${id}`, { method: "DELETE" });
  error.value = res.ok ? "" : "El autor tiene posts";
  await load();
}

async function publish() {
  await fetch("/api/posts", json("POST", { title: title.value, authorId: authorId.value }));
  title.value = "";
  await load();
}
</script>

<template>
  <div class="flex flex-col gap-4">
    <div class="flex gap-2">
      <input v-model="name" placeholder="Autor" />
      <button @click="createAuthor">Crear autor</button>
    </div>
    <div v-for="a in authors" :key="a.id" class="flex gap-2">
      <span>{{ a.name }}</span>
      <button @click="removeAuthor(a.id)">Borrar autor</button>
    </div>
    <span v-if="error" class="text-red-600">{{ error }}</span>
    <div class="flex gap-2">
      <input v-model="title" placeholder="Título" />
      <select v-model="authorId">
        <option value="" disabled>Autor del post</option>
        <option v-for="a in authors" :key="a.id" :value="a.id">{{ a.name }}</option>
      </select>
      <button @click="publish">Publicar</button>
    </div>
    <p v-for="p in posts" :key="p.id">{{ p.title }} por {{ p.author?.name }}</p>
  </div>
</template>

// benchmarks/eval/refs/fs-blog/react/App.tsx
import { useEffect, useState } from "react";

type Author = { id: string; name: string };
type Post = { id: string; title: string; author: Author | null };

export default function App() {
  const [authors, setAuthors] = useState<Author[]>([]);
  const [posts, setPosts] = useState<Post[]>([]);
  const [name, setName] = useState("");
  const [title, setTitle] = useState("");
  const [authorId, setAuthorId] = useState("");
  const [error, setError] = useState("");

  const load = async () => {
    setAuthors(await (await fetch("/api/authors")).json());
    setPosts(await (await fetch("/api/posts")).json());
  };
  useEffect(() => { load(); }, []);

  const json = (method: string, body: unknown) => ({ method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) });

  async function createAuthor() {
    await fetch("/api/authors", json("POST", { name }));
    setName("");
    load();
  }

  async function removeAuthor(id: string) {
    const res = await fetch(`/api/authors/${id}`, { method: "DELETE" });
    setError(res.ok ? "" : "El autor tiene posts");
    load();
  }

  async function publish() {
    await fetch("/api/posts", json("POST", { title, authorId }));
    setTitle("");
    load();
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="flex gap-2">
        <input placeholder="Autor" value={name} onChange={(e) => setName(e.target.value)} />
        <button onClick={createAuthor}>Crear autor</button>
      </div>
      {authors.map((a) => (
        <div key={a.id} className="flex gap-2">
          <span>{a.name}</span>
          <button onClick={() => removeAuthor(a.id)}>Borrar autor</button>
        </div>
      ))}
      {error && <span className="text-red-600">{error}</span>}
      <div className="flex gap-2">
        <input placeholder="Título" value={title} onChange={(e) => setTitle(e.target.value)} />
        <select value={authorId} onChange={(e) => setAuthorId(e.target.value)}>
          <option value="" disabled>Autor del post</option>
          {authors.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}
        </select>
        <button onClick={publish}>Publicar</button>
      </div>
      {posts.map((p) => <p key={p.id}>{p.title} por {p.author?.name}</p>)}
    </div>
  );
}
