// benchmarks/eval/refs/nav-layout/react/App.tsx
import { useEffect, useState, type MouseEvent } from "react";

export default function App() {
  const [path, setPath] = useState(location.pathname);
  const [likes, setLikes] = useState(0);
  useEffect(() => {
    const onPop = () => setPath(location.pathname);
    window.addEventListener("popstate", onPop);
    return () => window.removeEventListener("popstate", onPop);
  }, []);

  const go = (to: string) => (e: MouseEvent) => {
    e.preventDefault();
    history.pushState(null, "", to);
    setPath(to);
  };

  const profile = path.match(/^\/equipo\/([^/]+)$/);

  return (
    <div>
      <nav className="flex gap-3">
        <a href="/" onClick={go("/")}>Inicio</a>
        <a href="/equipo" onClick={go("/equipo")}>Equipo</a>
        <button onClick={() => setLikes(likes + 1)}>Me gusta</button>
        <span>Likes: {likes}</span>
      </nav>
      {path === "/" ? (
        <h1>Bienvenido</h1>
      ) : path === "/equipo" ? (
        <div className="flex flex-col gap-2">
          <h1>Nuestro equipo</h1>
          <a href="/equipo/ana" onClick={go("/equipo/ana")}>Ana</a>
          <a href="/equipo/beto" onClick={go("/equipo/beto")}>Beto</a>
        </div>
      ) : profile ? (
        <div className="flex flex-col gap-2">
          <h1>Perfil de {decodeURIComponent(profile[1])}</h1>
          <a href="/equipo" onClick={go("/equipo")}>Volver al equipo</a>
        </div>
      ) : (
        <h1>No encontrado</h1>
      )}
    </div>
  );
}

// benchmarks/eval/refs/nav-layout/svelte/App.svelte
<script lang="ts">
  let path = $state(location.pathname);
  let likes = $state(0);

  $effect(() => {
    const onPop = () => (path = location.pathname);
    window.addEventListener("popstate", onPop);
    return () => window.removeEventListener("popstate", onPop);
  });

  function go(e: MouseEvent, to: string) {
    e.preventDefault();
    history.pushState(null, "", to);
    path = to;
  }

  const member = $derived(path.match(/^\/equipo\/([^/]+)$/)?.[1]);
</script>

<nav class="flex gap-2">
  <a href="/" onclick={(e) => go(e, "/")}>Inicio</a>
  <a href="/equipo" onclick={(e) => go(e, "/equipo")}>Equipo</a>
  <button onclick={() => likes++}>Me gusta</button>
  <span>Likes: {likes}</span>
</nav>

{#if path === "/"}
  <h1>Bienvenido</h1>
{:else if path === "/equipo"}
  <h1>Nuestro equipo</h1>
  <a href="/equipo/ana" onclick={(e) => go(e, "/equipo/ana")}>Ana</a>
  <a href="/equipo/beto" onclick={(e) => go(e, "/equipo/beto")}>Beto</a>
{:else if member}
  <h1>Perfil de {member}</h1>
  <a href="/equipo" onclick={(e) => go(e, "/equipo")}>Volver al equipo</a>
{:else}
  <h1>No encontrado</h1>
{/if}
