// benchmarks/eval/refs/stopwatch/svelte/App.svelte
<script lang="ts">
  import { onDestroy } from "svelte";

  let time = $state(0);
  let timer: ReturnType<typeof setInterval> | undefined;

  function start() {
    if (timer) return;
    timer = setInterval(() => time++, 100);
  }

  function pause() {
    clearInterval(timer);
    timer = undefined;
  }

  function reset() {
    pause();
    time = 0;
  }

  onDestroy(pause);
</script>

<div class="flex flex-col gap-2">
  <p>Tiempo: {time}</p>
  <div class="flex gap-2">
    <button onclick={start}>Iniciar</button>
    <button onclick={pause}>Pausar</button>
    <button onclick={reset}>Reiniciar</button>
  </div>
</div>

// benchmarks/eval/refs/stopwatch/react/App.tsx
import { useEffect, useState } from "react";

export default function App() {
  const [time, setTime] = useState(0);
  const [running, setRunning] = useState(false);

  useEffect(() => {
    if (!running) return;
    const id = setInterval(() => setTime((t) => t + 1), 100);
    return () => clearInterval(id);
  }, [running]);

  function reset() {
    setRunning(false);
    setTime(0);
  }

  return (
    <div className="flex flex-col gap-2">
      <p>Tiempo: {time}</p>
      <div className="flex gap-2">
        <button onClick={() => setRunning(true)}>Iniciar</button>
        <button onClick={() => setRunning(false)}>Pausar</button>
        <button onClick={reset}>Reiniciar</button>
      </div>
    </div>
  );
}
