// benchmarks/eval/refs/fs-blog/vue/App.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";

type Author = { id: string; name: string };
type Post = { id: string; title: string; author: Author | null };

const authors = ref<Author[]>([]);
const posts = ref<Post[]>([]);
const name = ref("");
const title = ref("");
const authorId = ref("");
const error = ref("");

const json = (method: string, body: unknown) => ({ method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) });

async function load() {
  authors.value = await (await fetch("/api/authors")).json();
  posts.value = await (await fetch("/api/posts")).json();
}
onMounted(load);

async function createAuthor() {
  await fetch("/api/authors", json("POST", { name: name.value }));
  name.value = "";
  await load();
}

async function removeAuthor(id: string) {
  const res = await fetch(`/api/authors/${id}`, { method: "DELETE" });
  error.value = res.ok ? "" : "El autor tiene posts";
  await load();
}

async function publish() {
  await fetch("/api/posts", json("POST", { title: title.value, authorId: authorId.value }));
  title.value = "";
  await load();
}
</script>

<template>
  <div class="flex flex-col gap-4">
    <div class="flex gap-2">
      <input v-model="name" placeholder="Autor" />
      <button @click="createAuthor">Crear autor</button>
    </div>
    <div v-for="a in authors" :key="a.id" class="flex gap-2">
      <span>{{ a.name }}</span>
      <button @click="removeAuthor(a.id)">Borrar autor</button>
    </div>
    <span v-if="error" class="text-red-600">{{ error }}</span>
    <div class="flex gap-2">
      <input v-model="title" placeholder="Título" />
      <select v-model="authorId">
        <option value="" disabled>Autor del post</option>
        <option v-for="a in authors" :key="a.id" :value="a.id">{{ a.name }}</option>
      </select>
      <button @click="publish">Publicar</button>
    </div>
    <p v-for="p in posts" :key="p.id">{{ p.title }} por {{ p.author?.name }}</p>
  </div>
</template>

// benchmarks/eval/refs/fs-blog/svelte/App.svelte
<script lang="ts">
  type Author = { id: string; name: string };
  type Post = { id: string; title: string; author: Author | null };

  let authors = $state<Author[]>([]);
  let posts = $state<Post[]>([]);
  let name = $state("");
  let title = $state("");
  let authorId = $state("");
  let error = $state("");

  const json = (method: string, body: unknown) => ({ method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) });

  async function load() {
    authors = await (await fetch("/api/authors")).json();
    posts = await (await fetch("/api/posts")).json();
  }
  load();

  async function createAuthor() {
    await fetch("/api/authors", json("POST", { name }));
    name = "";
    await load();
  }

  async function removeAuthor(id: string) {
    const res = await fetch(`/api/authors/${id}`, { method: "DELETE" });
    error = res.ok ? "" : "El autor tiene posts";
    await load();
  }

  async function publish() {
    await fetch("/api/posts", json("POST", { title, authorId }));
    title = "";
    await load();
  }
</script>

<div class="flex flex-col gap-4">
  <div class="flex gap-2">
    <input placeholder="Autor" bind:value={name} />
    <button onclick={createAuthor}>Crear autor</button>
  </div>
  {#each authors as a (a.id)}
    <div class="flex gap-2">
      <span>{a.name}</span>
      <button onclick={() => removeAuthor(a.id)}>Borrar autor</button>
    </div>
  {/each}
  {#if error}<span class="text-red-600">{error}</span>{/if}
  <div class="flex gap-2">
    <input placeholder="Título" bind:value={title} />
    <select bind:value={authorId}>
      <option value="" disabled>Autor del post</option>
      {#each authors as a (a.id)}<option value={a.id}>{a.name}</option>{/each}
    </select>
    <button onclick={publish}>Publicar</button>
  </div>
  {#each posts as p (p.id)}<p>{p.title} por {p.author?.name}</p>{/each}
</div>
