// benchmarks/eval/refs/fs-tasks/solid/App.tsx
import { createResource, createSignal, For, Show } from "solid-js";

type Task = { id: string; title: string; done: boolean };

const json = (method: string, body: unknown) => ({ method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) });

export default function App() {
  const [tasks, { refetch }] = createResource<Task[]>(async () => (await fetch("/api/tasks")).json());
  const [title, setTitle] = createSignal("");
  const [filter, setFilter] = createSignal("Todas");
  const [renaming, setRenaming] = createSignal<string | null>(null);
  const [newTitle, setNewTitle] = createSignal("");

  const visible = () =>
    (tasks() ?? []).filter((t) => filter() === "Todas" || (filter() === "Hechas") === t.done);

  async function add() {
    await fetch("/api/tasks", json("POST", { title: title() }));
    setTitle("");
    refetch();
  }

  async function markDone(id: string) {
    await fetch(`/api/tasks/${id}`, json("PATCH", { done: true }));
    refetch();
  }

  function rename(task: Task) {
    setNewTitle(task.title);
    setRenaming(task.id);
  }

  async function save(id: string) {
    await fetch(`/api/tasks/${id}`, json("PATCH", { title: newTitle() }));
    setRenaming(null);
    refetch();
  }

  return (
    <div class="flex flex-col gap-2">
      <input placeholder="Tarea" value={title()} onInput={(e) => setTitle(e.currentTarget.value)} />
      <button onClick={add}>Agregar</button>
      <select value={filter()} onChange={(e) => setFilter(e.currentTarget.value)}>
        <option>Todas</option>
        <option>Pendientes</option>
        <option>Hechas</option>
      </select>
      <For each={visible()}>
        {(t) => (
          <div class="flex gap-2">
            <Show
              when={renaming() === t.id}
              fallback={<span>{t.title}{t.done ? " (hecha)" : ""}</span>}
            >
              <input placeholder="Nuevo título" value={newTitle()} onInput={(e) => setNewTitle(e.currentTarget.value)} />
              <button onClick={() => save(t.id)}>Guardar</button>
            </Show>
            <Show when={!t.done}>
              <button onClick={() => markDone(t.id)}>Hecha</button>
            </Show>
            <button onClick={() => rename(t)}>Renombrar</button>
          </div>
        )}
      </For>
    </div>
  );
}

// benchmarks/eval/refs/fs-tasks/react/App.tsx
import { useEffect, useState } from "react";

type Task = { id: string; title: string; done: boolean };

const json = (method: string, body: unknown) => ({ method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) });

export default function App() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [title, setTitle] = useState("");
  const [filter, setFilter] = useState("Todas");
  const [renaming, setRenaming] = useState<string | null>(null);
  const [newTitle, setNewTitle] = useState("");

  const load = () => fetch("/api/tasks").then((r) => r.json()).then(setTasks);
  useEffect(() => { load(); }, []);

  async function add() {
    await fetch("/api/tasks", json("POST", { title }));
    setTitle("");
    load();
  }

  async function markDone(id: string) {
    await fetch(`/api/tasks/${id}`, json("PATCH", { done: true }));
    load();
  }

  function rename(task: Task) {
    setRenaming(task.id);
    setNewTitle(task.title);
  }

  async function saveTitle(id: string) {
    await fetch(`/api/tasks/${id}`, json("PATCH", { title: newTitle }));
    setRenaming(null);
    load();
  }

  const visible = tasks.filter((t) => filter === "Todas" || (filter === "Hechas") === t.done);

  return (
    <div className="flex flex-col gap-2">
      <div className="flex gap-2">
        <input placeholder="Tarea" value={title} onChange={(e) => setTitle(e.target.value)} />
        <button onClick={add}>Agregar</button>
      </div>
      <select value={filter} onChange={(e) => setFilter(e.target.value)}>
        <option>Todas</option>
        <option>Pendientes</option>
        <option>Hechas</option>
      </select>
      {visible.map((t) => (
        <div key={t.id} className="flex gap-2">
          {renaming === t.id ? (
            <>
              <input placeholder="Nuevo título" value={newTitle} onChange={(e) => setNewTitle(e.target.value)} />
              <button onClick={() => saveTitle(t.id)}>Guardar</button>
            </>
          ) : (
            <span>{t.title}{t.done && " (hecha)"}</span>
          )}
          {!t.done && <button onClick={() => markDone(t.id)}>Hecha</button>}
          <button onClick={() => rename(t)}>Renombrar</button>
        </div>
      ))}
    </div>
  );
}
