// benchmarks/eval/refs/routes/svelte/App.svelte
<script lang="ts">
  const products = [{ id: 1, name: "Mesa" }, { id: 2, name: "Silla" }];
  let path = $state(location.pathname);

  $effect(() => {
    const onPop = () => (path = location.pathname);
    window.addEventListener("popstate", onPop);
    return () => window.removeEventListener("popstate", onPop);
  });

  function go(e: MouseEvent, to: string) {
    e.preventDefault();
    history.pushState(null, "", to);
    path = to;
  }

  const product = $derived.by(() => {
    const m = path.match(/^\/productos\/(\d+)$/);
    return m ? products.find((p) => p.id === Number(m[1])) : undefined;
  });
</script>

{#if path === "/"}
  <h1>Productos</h1>
  {#each products as p (p.id)}
    <div class="flex gap-2">
      <span>{p.name}</span>
      <a href={`/productos/${p.id}`} onclick={(e) => go(e, `/productos/${p.id}`)}>Ver</a>
    </div>
  {/each}
{:else if product}
  <h1>{product.name}</h1>
  <a href="/" onclick={(e) => go(e, "/")}>Volver</a>
{:else}
  <h1>No encontrado</h1>
{/if}

// benchmarks/eval/refs/routes/solid/App.tsx
import { createMemo, createSignal, For, Match, onCleanup, Switch } from "solid-js";

const products = [{ id: 1, name: "Mesa" }, { id: 2, name: "Silla" }];

export default function App() {
  const [path, setPath] = createSignal(location.pathname);
  const onPop = () => setPath(location.pathname);
  window.addEventListener("popstate", onPop);
  onCleanup(() => window.removeEventListener("popstate", onPop));

  const go = (to: string) => (e: MouseEvent) => {
    e.preventDefault();
    history.pushState(null, "", to);
    setPath(to);
  };
  const product = createMemo(() => {
    const m = path().match(/^\/productos\/(\d+)$/);
    return m ? products.find((p) => p.id === Number(m[1])) : undefined;
  });

  return (
    <Switch fallback={<h1>No encontrado</h1>}>
      <Match when={path() === "/"}>
        <h1>Productos</h1>
        <For each={products}>
          {(p) => (
            <div class="flex gap-2">
              <span>{p.name}</span>
              <a href={`/productos/${p.id}`} onClick={go(`/productos/${p.id}`)}>Ver</a>
            </div>
          )}
        </For>
      </Match>
      <Match when={product()}>
        {(p) => (
          <>
            <h1>{p().name}</h1>
            <a href="/" onClick={go("/")}>Volver</a>
          </>
        )}
      </Match>
    </Switch>
  );
}
