// benchmarks/eval/refs/routes/vue/App.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from "vue";

const products = [{ id: 1, name: "Mesa" }, { id: 2, name: "Silla" }];
const path = ref(location.pathname);
const onPop = () => (path.value = location.pathname);
onMounted(() => window.addEventListener("popstate", onPop));
onUnmounted(() => window.removeEventListener("popstate", onPop));

function go(e: MouseEvent, to: string) {
  e.preventDefault();
  history.pushState(null, "", to);
  path.value = to;
}

const product = computed(() => {
  const m = path.value.match(/^\/productos\/(\d+)$/);
  return m ? products.find((p) => p.id === Number(m[1])) : undefined;
});
</script>

<template>
  <div v-if="path === '/'">
    <h1>Productos</h1>
    <div v-for="p in products" :key="p.id" class="flex gap-2">
      <span>{{ p.name }}</span>
      <a :href="`/productos/${p.id}`" @click="go($event, `/productos/${p.id}`)">Ver</a>
    </div>
  </div>
  <div v-else-if="product">
    <h1>{{ product.name }}</h1>
    <a href="/" @click="go($event, '/')">Volver</a>
  </div>
  <h1 v-else>No encontrado</h1>
</template>

// benchmarks/eval/refs/routes/svelte/App.svelte
<script lang="ts">
  const products = [{ id: 1, name: "Mesa" }, { id: 2, name: "Silla" }];
  let path = $state(location.pathname);

  $effect(() => {
    const onPop = () => (path = location.pathname);
    window.addEventListener("popstate", onPop);
    return () => window.removeEventListener("popstate", onPop);
  });

  function go(e: MouseEvent, to: string) {
    e.preventDefault();
    history.pushState(null, "", to);
    path = to;
  }

  const product = $derived.by(() => {
    const m = path.match(/^\/productos\/(\d+)$/);
    return m ? products.find((p) => p.id === Number(m[1])) : undefined;
  });
</script>

{#if path === "/"}
  <h1>Productos</h1>
  {#each products as p (p.id)}
    <div class="flex gap-2">
      <span>{p.name}</span>
      <a href={`/productos/${p.id}`} onclick={(e) => go(e, `/productos/${p.id}`)}>Ver</a>
    </div>
  {/each}
{:else if product}
  <h1>{product.name}</h1>
  <a href="/" onclick={(e) => go(e, "/")}>Volver</a>
{:else}
  <h1>No encontrado</h1>
{/if}
