// benchmarks/eval/projects/shop/svelte/CartView.svelte
<script lang="ts">
  import type { CartItem } from "./data";
  import CartItemRow from "./CartItemRow.svelte";
  import Summary from "./Summary.svelte";

  let { cart, onChangeQty, onClear }: { cart: CartItem[]; onChangeQty: (id: number, delta: number) => void; onClear: () => void } = $props();
</script>

{#if cart.length === 0}
  <span class="text-gray-500">El carrito está vacío</span>
{:else}
  <div class="flex flex-col gap-2">
    {#each cart as item (item.product.id)}
      <CartItemRow {item} onChangeQty={(d) => onChangeQty(item.product.id, d)} />
    {/each}
    <Summary {cart} {onClear} />
  </div>
{/if}

// benchmarks/eval/projects/shop/solid/CartView.tsx
import { For, Show } from "solid-js";
import type { CartItem } from "./data";
import CartItemRow from "./CartItemRow";
import Summary from "./Summary";

type Props = { cart: CartItem[]; onChangeQty: (id: number, delta: number) => void; onClear: () => void };

export default function CartView(props: Props) {
  return (
    <Show when={props.cart.length > 0} fallback={<span class="text-gray-500">El carrito está vacío</span>}>
      <div class="flex flex-col gap-2">
        <For each={props.cart}>{(item) => <CartItemRow item={item} onChangeQty={(d) => props.onChangeQty(item.product.id, d)} />}</For>
        <Summary cart={props.cart} onClear={props.onClear} />
      </div>
    </Show>
  );
}
